[2021-01-05 10:49:25,598][Thread-1:3008][task_id:root][views.py:10][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 14:14:50,167][Thread-199:2672][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-05 14:50:52,148][Thread-64:2304][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 14:50:55,641][Thread-70:12144][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 14:50:56,267][Thread-72:3880][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 14:50:59,275][Thread-74:9120][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 14:51:24,190][Thread-78:17700][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:17:03,907][Thread-100:18048][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-05 15:20:49,536][Thread-105:3948][task_id:django.request][base.py:152][WARNING][Not Found: //static/img/p_big3.jpg]
[2021-01-05 15:20:49,651][Thread-106:16432][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-05 15:22:57,407][Thread-132:10108][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:23:34,664][Thread-134:11184][task_id:django.security.csrf][csrf.py:160][WARNING][Forbidden (CSRF token missing or incorrect.): /test/test.html]
[2021-01-05 15:23:34,720][Thread-135:2936][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-05 15:49:24,392][Thread-310:6532][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:50:48,135][Thread-1:10332][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:50:48,147][Thread-1:10332][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\PycharmProjects\cmdb\cmdb\views.py", line 13, in index
    return render(request, 'index.html')
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python27\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'extends' cannot appear more than once in the same template
[2021-01-05 15:50:48,502][Thread-3:3628][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-05 15:55:20,815][Thread-30:3924][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:55:22,140][Thread-40:11676][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:55:22,641][Thread-51:9104][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:55:23,033][Thread-62:17812][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:55:23,701][Thread-73:18044][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:55:23,977][Thread-84:10892][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:55:24,236][Thread-95:18328][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:55:24,523][Thread-106:7260][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 15:55:24,763][Thread-117:636][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:08:19,002][Thread-180:18212][task_id:django.request][base.py:152][WARNING][Not Found: /register/]
[2021-01-05 16:08:19,078][Thread-181:7192][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-05 16:15:12,614][Thread-230:3172][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:15:27,413][Thread-233:1576][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:16:51,713][Thread-240:7720][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:18:07,540][Thread-242:4272][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:18:08,941][Thread-244:18336][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:18:09,334][Thread-246:2952][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:18:38,614][Thread-248:244][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:18:44,736][Thread-250:5464][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:20:27,516][Thread-252:16532][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:20:29,332][Thread-254:18336][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:20:29,657][Thread-256:6108][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:20:29,934][Thread-258:5424][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:20:30,213][Thread-260:14328][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:20:30,530][Thread-262:15876][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:20:31,017][Thread-264:3320][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:22:29,933][Thread-266:15328][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:22:31,072][Thread-268:13528][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 16:23:13,868][Thread-270:16608][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-05 19:04:10,713][Thread-1:17728][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-06 10:13:22,778][Thread-5:18696][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-06 10:58:23,190][Thread-1:21444][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-06 16:34:46,523][Thread-3:19588][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 15:55:31,440][Thread-127:19788][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 16:33:14,835][Thread-315:23076][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:03:43,219][Thread-843:25112][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:48:53,394][Thread-982:19564][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 18:53:37,026][Thread-991:16232][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:53:49,207][Thread-995:18392][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:53:49,747][Thread-999:17796][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:54:58,111][Thread-1003:20812][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:54:58,171][Thread-1004:24000][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:54:58,180][Thread-1005:19484][task_id:django.request][base.py:152][WARNING][Not Found: /js/jquery.min.js]
[2021-01-07 18:54:58,183][Thread-1006:24008][task_id:django.request][base.py:152][WARNING][Not Found: /js/vector.js]
[2021-01-07 18:54:58,799][Thread-1008:23908][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:54:58,858][Thread-1009:7516][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:54:58,865][Thread-1010:18720][task_id:django.request][base.py:152][WARNING][Not Found: /js/jquery.min.js]
[2021-01-07 18:54:58,865][Thread-1011:25008][task_id:django.request][base.py:152][WARNING][Not Found: /js/vector.js]
[2021-01-07 18:54:59,108][Thread-1013:25016][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:54:59,164][Thread-1014:24644][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:54:59,171][Thread-1015:22136][task_id:django.request][base.py:152][WARNING][Not Found: /js/jquery.min.js]
[2021-01-07 18:54:59,174][Thread-1016:19304][task_id:django.request][base.py:152][WARNING][Not Found: /js/vector.js]
[2021-01-07 18:54:59,351][Thread-1018:23560][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:54:59,421][Thread-1019:18108][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:54:59,424][Thread-1020:16700][task_id:django.request][base.py:152][WARNING][Not Found: /js/jquery.min.js]
[2021-01-07 18:54:59,427][Thread-1021:3632][task_id:django.request][base.py:152][WARNING][Not Found: /js/vector.js]
[2021-01-07 18:55:31,148][Thread-1023:22844][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:55:31,211][Thread-1026:13140][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:55:31,250][Thread-1028:25232][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:55:31,749][Thread-1030:19044][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:55:31,805][Thread-1034:20344][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:55:31,835][Thread-1035:23240][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:55:32,019][Thread-1037:21920][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:55:32,073][Thread-1040:18440][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:55:32,101][Thread-1042:18696][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:55:32,253][Thread-1045:23688][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:55:32,319][Thread-1047:18312][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:55:32,358][Thread-1049:25140][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:56:58,177][Thread-1052:21472][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:56:58,227][Thread-1053:7944][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:56:58,253][Thread-1054:24908][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:56:58,938][Thread-1056:10956][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:56:58,990][Thread-1057:268][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:56:59,332][Thread-1059:21480][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:56:59,390][Thread-1060:9624][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:57:17,749][Thread-1062:22228][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:57:17,803][Thread-1063:25528][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:57:17,924][Thread-1064:3312][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 18:57:31,378][Thread-1065:13564][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:57:31,418][Thread-1066:24020][task_id:django.request][base.py:152][WARNING][Not Found: /css/style.css]
[2021-01-07 18:59:05,490][Thread-1067:24452][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 18:59:06,190][Thread-1069:23944][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 19:06:51,907][Thread-1089:12764][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /accounts/login/]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.accounts.views.Account_Login didn't return an HttpResponse object. It returned None instead.
[2021-01-07 19:07:12,619][Thread-1090:17456][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /accounts/login/]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.accounts.views.Account_Login didn't return an HttpResponse object. It returned None instead.
[2021-01-07 19:07:18,023][Thread-1094:12036][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /accounts/login/]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.accounts.views.Account_Login didn't return an HttpResponse object. It returned None instead.
[2021-01-07 19:08:04,648][Thread-1096:24476][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /accounts/login/]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.accounts.views.Account_Login didn't return an HttpResponse object. It returned None instead.
[2021-01-07 19:08:18,696][Thread-1097:18652][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 19:08:39,736][Thread-1100:15760][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /accounts/login/]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.accounts.views.Account_Login didn't return an HttpResponse object. It returned None instead.
[2021-01-07 19:09:56,273][Thread-1103:9152][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /accounts/login/]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.accounts.views.Account_Login didn't return an HttpResponse object. It returned None instead.
[2021-01-07 19:10:25,759][Thread-1104:13140][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /accounts/login/]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.accounts.views.Account_Login didn't return an HttpResponse object. It returned None instead.
[2021-01-07 19:15:15,404][Thread-1113:18748][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 19:15:59,617][Thread-1114:14816][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 19:16:16,273][Thread-1121:19072][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 19:39:57,308][Thread-1145:13496][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 19:42:24,081][Thread-1148:4420][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 19:43:06,385][Thread-1154:24960][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:43:07,253][Thread-1159:23832][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:43:14,839][Thread-1164:3272][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:43:15,387][Thread-1169:5032][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:45:32,696][Thread-1193:19248][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:45:33,177][Thread-1198:24480][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:53:24,530][Thread-1222:23776][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:53:54,068][Thread-1229:21508][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:53:54,921][Thread-1234:3508][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:54:17,494][Thread-1241:13316][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:54:35,927][Thread-1246:25340][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 19:54:36,591][Thread-1251:22688][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 20:05:47,780][Thread-1276:22348][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 20:05:49,038][Thread-1282:17012][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2021-01-07 20:12:53,483][Thread-1309:24276][task_id:django.request][base.py:152][WARNING][Not Found: /register/]
[2021-01-07 20:12:59,969][Thread-1310:22648][task_id:django.request][base.py:152][WARNING][Not Found: /account/register/]
[2021-01-07 20:14:00,092][Thread-1314:21120][task_id:django.security.csrf][csrf.py:160][WARNING][Forbidden (CSRF token missing or incorrect.): /login/]
[2021-01-07 20:14:22,207][Thread-1315:16952][task_id:django.security.csrf][csrf.py:160][WARNING][Forbidden (CSRF token missing or incorrect.): /login/]
[2021-01-07 20:14:24,973][Thread-1316:12036][task_id:django.security.csrf][csrf.py:160][WARNING][Forbidden (CSRF token missing or incorrect.): /login/]
[2021-01-07 20:14:29,368][Thread-1320:22832][task_id:root][views.py:12][INFO][<WSGIRequest: GET '/'>]
[2021-01-07 20:14:36,930][Thread-1322:2112][task_id:django.request][base.py:152][WARNING][Not Found: /register]
[2021-01-07 20:16:55,355][Thread-6:14744][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /accounts/register/]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\PycharmProjects\cmdb\apps\accounts\views.py", line 25, in Account_Register
    User.objects.create_user(username=username, password=password)
  File "C:\Python27\lib\site-packages\django\contrib\auth\models.py", line 159, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "C:\Python27\lib\site-packages\django\contrib\auth\models.py", line 153, in _create_user
    user.save(using=self._db)
  File "C:\Python27\lib\site-packages\django\contrib\auth\base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python27\lib\site-packages\django\db\models\base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: column username is not unique
